### ISSUE TITLE
Mention dependencies in readme

### ISSUE THREAD

**Issue by sman591** [nmpiazza/Least-Load-SSH#1]
This requires `pxssh`, which looks to be part of `pexpect`. The readme should mention this for anyone starting out that doesn't know how to handle python dependencies; something along the lines of what's on the docs:

http://pexpect.readthedocs.org/en/latest/install.html

**Comment by nmpiazza** [comment]
Updated.  Enough detail?

**Comment by sman591** [comment]
:+1:
